[projects.koados]
path = "~/.koad-os"
github_owner = "DoodzCode"
github_repo = "koad-os"
credential_key = "GITHUB_PERSONAL_PAT"

[projects.skylinks]
path = "~/data/skylinks"
github_owner = "Skylinks-Golf"
credential_key = "GITHUB_SKYLINKS_FULLACCESS_TOKEN"
