# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kernel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kernel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckernel.proto\x12\x0bkoad.kernel\"\xa6\x01\n\x0e\x43ommandRequest\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x33\n\x04\x61rgs\x18\x03 \x03(\x0b\x32%.koad.kernel.CommandRequest.ArgsEntry\x12\x10\n\x08identity\x18\x04 \x01(\t\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"U\n\x0f\x43ommandResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"k\n\x0fTelemetryUpdate\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12$\n\x05level\x18\x04 \x01(\x0e\x32\x15.koad.kernel.LogLevel\"\x07\n\x05\x45mpty*4\n\x08LogLevel\x12\x08\n\x04INFO\x10\x00\x12\x08\n\x04WARN\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\t\n\x05\x44\x45\x42UG\x10\x03\x32\xd1\x01\n\rKernelService\x12\x44\n\x07\x45xecute\x12\x1b.koad.kernel.CommandRequest\x1a\x1c.koad.kernel.CommandResponse\x12\x45\n\x0fStreamTelemetry\x12\x12.koad.kernel.Empty\x1a\x1c.koad.kernel.TelemetryUpdate0\x01\x12\x33\n\tHeartbeat\x12\x12.koad.kernel.Empty\x1a\x12.koad.kernel.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kernel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST_ARGSENTRY']._loaded_options = None
  _globals['_COMMANDREQUEST_ARGSENTRY']._serialized_options = b'8\001'
  _globals['_LOGLEVEL']._serialized_start=403
  _globals['_LOGLEVEL']._serialized_end=455
  _globals['_COMMANDREQUEST']._serialized_start=30
  _globals['_COMMANDREQUEST']._serialized_end=196
  _globals['_COMMANDREQUEST_ARGSENTRY']._serialized_start=153
  _globals['_COMMANDREQUEST_ARGSENTRY']._serialized_end=196
  _globals['_COMMANDRESPONSE']._serialized_start=198
  _globals['_COMMANDRESPONSE']._serialized_end=283
  _globals['_TELEMETRYUPDATE']._serialized_start=285
  _globals['_TELEMETRYUPDATE']._serialized_end=392
  _globals['_EMPTY']._serialized_start=394
  _globals['_EMPTY']._serialized_end=401
  _globals['_KERNELSERVICE']._serialized_start=458
  _globals['_KERNELSERVICE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
