# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skill.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'skill.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bskill.proto\x12\nkoad.skill\"\x93\x01\n\nRunRequest\x12\x10\n\x08skill_id\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\x12\x34\n\x07\x63ontext\x18\x03 \x03(\x0b\x32#.koad.skill.RunRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Q\n\tRunUpdate\x12\x10\n\x08skill_id\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x01\x12\x10\n\x08\x66inished\x18\x04 \x01(\x08\"\x98\x01\n\x0cStatusUpdate\x12\x10\n\x08skill_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x36\n\x07metrics\x18\x03 \x03(\x0b\x32%.koad.skill.StatusUpdate.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x07\n\x05\x45mpty2\x83\x01\n\x0cSkillService\x12\x36\n\x03Run\x12\x16.koad.skill.RunRequest\x1a\x15.koad.skill.RunUpdate0\x01\x12;\n\x0cReportStatus\x12\x18.koad.skill.StatusUpdate\x1a\x11.koad.skill.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skill_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_RUNREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_STATUSUPDATE_METRICSENTRY']._loaded_options = None
  _globals['_STATUSUPDATE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_RUNREQUEST']._serialized_start=28
  _globals['_RUNREQUEST']._serialized_end=175
  _globals['_RUNREQUEST_CONTEXTENTRY']._serialized_start=129
  _globals['_RUNREQUEST_CONTEXTENTRY']._serialized_end=175
  _globals['_RUNUPDATE']._serialized_start=177
  _globals['_RUNUPDATE']._serialized_end=258
  _globals['_STATUSUPDATE']._serialized_start=261
  _globals['_STATUSUPDATE']._serialized_end=413
  _globals['_STATUSUPDATE_METRICSENTRY']._serialized_start=367
  _globals['_STATUSUPDATE_METRICSENTRY']._serialized_end=413
  _globals['_EMPTY']._serialized_start=415
  _globals['_EMPTY']._serialized_end=422
  _globals['_SKILLSERVICE']._serialized_start=425
  _globals['_SKILLSERVICE']._serialized_end=556
# @@protoc_insertion_point(module_scope)
